### ISSUE TITLE
Unable to refresh User lists

### ISSUE THREAD

**Issue by CamilleHbp** [dexter21767/Trakt#12]
I installed the add-on sometime ago. I realised that I am missing a personal list from the `discover/Trakt` tab.

I've updated the lists when configuring the add-on, the list still doesn't show. 

I've then uninstalled the add-on, quit Stremio, re-launched Stremio and re-installed the add-on, yet it still shows the old lists and does not refresh the discover list.

Thank you for your work on the add-on. Could you take a look? Thanks! 👍

**Comment by dexter21767** [comment]
i think this was fixed a while ago, can you confirm please?

**Comment by CamilleHbp** [comment]
I think it's working fine now. I pretty much forgot what was the problem I had a year ago 😂

**Comment by dexter21767** [comment]
i fixed a bunch of issues and didn't close them and forgot which ones i fixed, so now i am making sure which ones are fixe.

**Comment by CamilleHbp** [comment]
Well I thought it was working, but it isn't. I don't really use Stremio for local files now, because of this ^^ Too bad I can't track my viewings through it, but I manage :D
