### ISSUE TITLE
Lists should not default to "Rank Ascendant" sorting

### ISSUE THREAD

**Issue by who-is-matt** [dexter21767/Trakt#18]
Trakt considers the #1 ranked item on a list to be the "highest" ranked, despite being the lowest numbered.  The Trakt addon defaults to "Rank Ascendant" sorting for user-added lists, which is presumably based on the idea that the list would start with the #1 item. 

Because the sorting options for the Trakt addon are grayed out and not highly visible, it's likely that many users will fail to notice them, and assume that the lists will appear in Stremio in the same order as they appear on Trakt.  But because the Trakt addon defaults to "Rank Ascendant", those lists will actually be shown in the opposite order in Stremio.

A simple fix would be to default user-added lists in the Trakt addon to "Rank Descendant".  It may also be helpful if the sorting options for user-added lists were slightly more noticeable than the current light-gray text.

**Comment by dexter21767** [comment]
@who-is-matt just to be clear, the addon doesn't default to "Rank Ascendant", it defaults to whatever is set in the list's config. to edit that, u need to go to your list's page, click on the edit pen (next to the delete X) and whatever sorting u select there will be the default sorting for the list.
![image](https://github.com/dexter21767/Trakt/assets/88626454/f313d579-81a1-4f3e-b5e4-ce17c47c7766)
and regarding the light-gray text, yes it might be better to change the colors.

**Comment by soliviantar** [comment]
Hi, @dexter21767. I followed your instructions to change the order of my watchlist (changed to rating descendent) and I can't see it having any effect, all the movies are still listed by "rank".

I don't have any other personal lists, only the default watchlist. Is that the reason why this doesn't work? Adding to the watchlist is the easiest, imo, so I'd really prefer it I could change the order of the list.

**Comment by dexter21767-dev** [comment]
there's already an option to change the default sorting on the config page. please test it and if it works as it should close this issue, and if there are problems with it please let me know.
![image](https://github.com/dexter21767/Trakt/assets/127498984/d6f9598c-9222-4e3e-90cd-d94bffc675d0)

**Comment by soliviantar** [comment]
> there's already an option to change the default sorting on the config page. please test it and if it works as it should close this issue, and if there are problems with it please let me know. 

Thanks, yes, I already tried that. In fact that was the first thing I tried. Since it didn't work, I came here via Reddit and tried changing the original trakt list order instead. 

None of those work, unfortunately. :(

**Comment by mrkPavel** [comment]
Hi @dexter21767-dev , for me changing the sorting from the config page only works when the Watchlist is set to Divided.
When the Watchlist is set to Merged, the sorting choice is ignored.
