### ISSUE TITLE
Cannot see individual episodes from Trakt Lists

### ISSUE THREAD

**Issue by Brandon1212b** [dexter21767/Trakt#19]
Created a list with Christmas Episodes and Movies, but only the movies show up. It seems this addon cannot add individual episodes to the list. Here the list i'm trying to add: https://trakt.tv/users/brandon1212b/lists/bfabs-christmas-list?sort=popularity,asc

**Comment by dexter21767** [comment]
yes, individual episodes are currently unseported.
