### ISSUE TITLE
Show/Movie page is missing the share icon 

### ISSUE THREAD

**Issue by soliviantar** [dexter21767/Trakt#23]
Hi. I noticed that when I go into a movie details page from this addon, the share button is not available. But when I get to the page from the cinemeta search results, the share button appears on the upper right corner.

Could this be fixed? Thanks!

**Comment by dexter21767** [comment]
can you provide more context? 
i tested it on stremio-web and it's working fine. 
please provide info about what platform and app and which version are u using. and if it's not happening on all movies or lists, tell me which ones aren't working so i can test.

**Comment by soliviantar** [comment]
Hi @dexter21767 ,

this is happening on Android, app version 1.6.12. I can reproduce this with all movies/shows on all lists as far as I can see.

**Comment by dexter21767** [comment]
@soliviantar then this is a bug with stremio android, 
please make an issue for it here so the stremio team can fix it.
https://github.com/Stremio/stremio-bugs/issues
