### ISSUE TITLE
Unable to renew or update Trakt token

### ISSUE THREAD

**Issue by RYJASM** [dexter21767/Trakt#24]
Opening the config for this Stremio plugin shows an "Authenticated" button and an expired token date with no way to renew it or change it or remove it or add a new one.

**Comment by dexter21767** [comment]
can you attach a screenshot and/or the config URL, please?

**Comment by effie02** [comment]
![Screenshot_20240501_170744_Firefox](https://github.com/dexter21767/Trakt/assets/78867920/ff3a0608-b52d-41db-b7a1-df55b1452542)
Same issue here. Lists (besides generic) won't show up in Stremio anymore

**Comment by dexter21767** [comment]
@effie02 thank you for providing the URL, the addon has been updated and the issue fixed.
