### ISSUE TITLE
Proper list randomization

### ISSUE THREAD

**Issue by cgio** [dexter21767/Trakt#27]
Solution:

Append `?r={TIMESTAMP}` to URL. In other words, add code to generate the timestamp for the current moment and append that to the URL for all "genre=random" GET requests.

...This prevents the caching problem and force randomization to occur. Please implement where the list sort type is set to random, both ascending and descending.

For example:
`https://2ecbbd610840-trakt.baby-beamup.club/{LIST-STUFF}/genre=random%20asc.json?r=1718121008`

(People have asked for this; see https://www.reddit.com/r/StremioAddons/comments/1ap36a1/trakt_on_stremio_is_there_a_way_to_make_the_trakt/)

**Comment by dexter21767** [comment]
> Append ?r={TIMESTAMP} to URL. In other words, add code to generate the timestamp for the current moment and append that to the URL for all "genre=random" GET requests.

that's not how it works, stremio generates the links, not the addon.
but i implemented something to fix it, might revert if that caused the server to overload.

**Comment by ohnoPNG** [comment]
is it still really random?
