### ISSUE TITLE
[REQUEST] display added list as per sort setting in Trakt ?

### ISSUE THREAD

**Issue by cojoMan** [dexter21767/Trakt#3]
Currently you can set your list on the Trakt website to have a custom sort. I keep most of them to "recently added" or "latest release".
I would be great if this sort would be kept when added to stremio. If I add a new item to a list, to have it at the front for example, or just by changing the sort on trakt, to update the list on Stremio. Is that something that can be done ?
Thank you.

**Comment by dexter21767** [comment]
you can easily do that by adding the lists via the link option.
for example
https://trakt.tv/users/giladg/lists/latest-releases?sort=added,asc
this link will default to sorting by added ascending. "?sort=added,asc"
so just open the menu on trakt with the desired sorting option. then copy the link and added it to the config page.
