### ISSUE TITLE
Streamio not auto updating Trakt list and vice versa

### ISSUE THREAD

**Issue by MayoPonyo** [dexter21767/Trakt#36]
If I add a movie or show on Trakt, my library in Streamio is not auto-updated.
Same if I mark as watched a movei or show in Streamio, my trakt info is not updated.

**Comment by derrgoo** [comment]
I have noticed this also. Watchlist movies if wat he'd it stays on trakt list on stremio trakt section.

**Comment by dexter21767** [comment]
@MayoPonyo if u want to import your library into stremio, u need to go to [account settings in stremio's website](https://www.stremio.com/acc-settings) then scroll down to integration and click import.
