### ISSUE TITLE
Can't add it

### ISSUE THREAD

**Issue by MrKaon** [dexter21767/Trakt#5]
Used to work fine, but disappeared from installed add-on list , also can't reinstall it again using this [Page](https://2ecbbd610840-trakt.baby-beamup.club/configure/?access_token=1cc66137345c7ff161175132c43fa237d72f636e3b275f561df35336df8fe994)  getting error add-on can't install.
Using latest Stremio on Android.

**Comment by dexter21767** [comment]
should be working fine now
