### ISSUE TITLE
unable to browse and add personal lists

### ISSUE THREAD

**Issue by tes36** [dexter21767/Trakt#7]
I can browse popular and trending lists but i can't browse personal lists.

It says I'm autherized (logged)

![image](https://user-images.githubusercontent.com/123871375/216626753-c27500b7-a7f0-47e0-a9e5-d9fc049d1b23.png)

**Comment by dexter21767** [comment]
what do u mean by u can't? 
what happens when u click on "browse personal lists"?

**Comment by ViVi93** [comment]
![Screenshot_2023-04-07-11-50-26-989_com kiwibrowser browser dev](https://user-images.githubusercontent.com/24795794/230553286-3835db2d-97f0-46a0-8124-389a83e3d959.jpg)

Im also facing the same issue, just seeing a blank pop up screen when i click on personal lists
